In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("ocorrencia.csv", sep=";", parse_dates=['ocorrencia_dia'],dayfirst=True)
df.head()

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
0,52242,52242,52242,52242,52242,INCIDENTE,NaN,NaN,PORTO ALEGRE,RS,...,2012-01-05,20:27:00,***,FINALIZADA,***,NÃO,NaN,0,1,NÃO
1,45331,45331,45331,45331,45331,ACIDENTE,-23.4355555556,-46.4730555556,GUARULHOS,SP,...,2012-01-06,13:44:00,SIM,FINALIZADA,A-582/CENIPA/2014,SIM,2016-09-01,3,1,NÃO
2,45333,45333,45333,45333,45333,ACIDENTE,***,***,VIAMÃO,RS,...,2012-01-06,13:00:00,NaN,FINALIZADA,A-070/CENIPA/2013,SIM,2013-11-27,0,1,NÃO
3,45401,45401,45401,45401,45401,ACIDENTE,***,***,SÃO SEBASTIÃO,SP,...,2012-01-06,17:00:00,***,NaN,NaN,NÃO,NaN,0,1,NÃO
4,45407,45407,45407,45407,45407,ACIDENTE,***,***,SÃO SEPÉ,RS,...,2012-01-06,16:30:00,SIM,FINALIZADA,A-071/CENIPA/2013,SIM,2013-11-27,0,1,NÃO

In [3]:
df.loc[1,"ocorrencia_cidade"]
#Consulta de um dado específico na interseção linha X coluna

'GUARULHOS'

In [4]:
df.loc[1:3]
#Consulta de um intervalo de linhas

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
1,45331,45331,45331,45331,45331,ACIDENTE,-23.4355555556,-46.4730555556,GUARULHOS,SP,...,2012-01-06,13:44:00,SIM,FINALIZADA,A-582/CENIPA/2014,SIM,2016-09-01,3,1,NÃO
2,45333,45333,45333,45333,45333,ACIDENTE,***,***,VIAMÃO,RS,...,2012-01-06,13:00:00,NaN,FINALIZADA,A-070/CENIPA/2013,SIM,2013-11-27,0,1,NÃO
3,45401,45401,45401,45401,45401,ACIDENTE,***,***,SÃO SEBASTIÃO,SP,...,2012-01-06,17:00:00,***,NaN,NaN,NÃO,NaN,0,1,NÃO

In [5]:
df.loc[[10,21,40]]
#Consulta linhas específicas, neste caso as linhas 10,21 e 40

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
10,45332,45332,45332,45332,45332,ACIDENTE,***,***,VIAMÃO,RS,...,2012-01-09,13:30:00,SIM,FINALIZADA,A-072/CENIPA/2013,SIM,2013-11-27,0,1,NÃO
21,45392,45392,45392,45392,45392,ACIDENTE,-15.8197222222,-47.8747222222,BRASÍLIA,DF,...,2012-01-19,21:30:00,SIM,FINALIZADA,A-032/CENIPA/2014,SIM,2014-04-07,2,1,NÃO
40,45415,45415,45415,45415,45415,ACIDENTE,***,***,RIO DE JANEIRO,RJ,...,2012-01-30,13:55:00,SIM,FINALIZADA,A-077/CENIPA/2013,SIM,2013-10-21,0,1,NÃO

In [6]:
df.loc[:,'ocorrencia_aerodromo']
#Consulta de uma coluna inteira

0        SBPA
1        SBGR
2        ****
3        ****
4        ****
        ...
5162     ####
5163    *****
5164     SSNH
5165     SBBI
5166     SBPL
Name: ocorrencia_aerodromo, Length: 5167, dtype: object

In [7]:
df.codigo_ocorrencia.is_unique
#Verifica se cada dado da coluna citada é único, ou seja, se cada dado daquela coluna é diferente do outro

True

In [8]:
df.set_index('codigo_ocorrencia', inplace=True)
#Transforma a coluna especificada em índice e o comando (inplace=True) altera o arquivo

In [9]:
df.head()

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
codigo_ocorrencia,,,,,,,,,,,,,,,,,,,,,
52242,52242,52242,52242,52242,INCIDENTE,NaN,NaN,PORTO ALEGRE,RS,BRASIL,...,2012-01-05,20:27:00,***,FINALIZADA,***,NÃO,NaN,0,1,NÃO
45331,45331,45331,45331,45331,ACIDENTE,-23.4355555556,-46.4730555556,GUARULHOS,SP,BRASIL,...,2012-01-06,13:44:00,SIM,FINALIZADA,A-582/CENIPA/2014,SIM,2016-09-01,3,1,NÃO
45333,45333,45333,45333,45333,ACIDENTE,***,***,VIAMÃO,RS,BRASIL,...,2012-01-06,13:00:00,NaN,FINALIZADA,A-070/CENIPA/2013,SIM,2013-11-27,0,1,NÃO
45401,45401,45401,45401,45401,ACIDENTE,***,***,SÃO SEBASTIÃO,SP,BRASIL,...,2012-01-06,17:00:00,***,NaN,NaN,NÃO,NaN,0,1,NÃO
45407,45407,45407,45407,45407,ACIDENTE,***,***,SÃO SEPÉ,RS,BRASIL,...,2012-01-06,16:30:00,SIM,FINALIZADA,A-071/CENIPA/2013,SIM,2013-11-27,0,1,NÃO

In [10]:
df.loc[45407]

codigo_ocorrencia1                              45407
codigo_ocorrencia2                              45407
codigo_ocorrencia3                              45407
codigo_ocorrencia4                              45407
ocorrencia_classificacao                     ACIDENTE
ocorrencia_latitude                               ***
ocorrencia_longitude                              ***
ocorrencia_cidade                            SÃO SEPÉ
ocorrencia_uf                                      RS
ocorrencia_pais                                BRASIL
ocorrencia_aerodromo                             ****
ocorrencia_dia                    2012-01-06 00:00:00
ocorrencia_hora                              16:30:00
investigacao_aeronave_liberada                    SIM
investigacao_status                        FINALIZADA
divulgacao_relatorio_numero         A-071/CENIPA/2013
divulgacao_relatorio_publicado                    SIM
divulgacao_dia_publicacao                  2013-11-27
total_recomendacoes                                 0
total_aeronaves_envolvidas                          1
ocorrencia_saida_pista                            NÃO
Name: 45407, dtype: object

In [11]:
df.reset_index(drop=True,inplace=True)
#Reseta o índice

In [12]:
df.head()

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
0,52242,52242,52242,52242,INCIDENTE,NaN,NaN,PORTO ALEGRE,RS,BRASIL,...,2012-01-05,20:27:00,***,FINALIZADA,***,NÃO,NaN,0,1,NÃO
1,45331,45331,45331,45331,ACIDENTE,-23.4355555556,-46.4730555556,GUARULHOS,SP,BRASIL,...,2012-01-06,13:44:00,SIM,FINALIZADA,A-582/CENIPA/2014,SIM,2016-09-01,3,1,NÃO
2,45333,45333,45333,45333,ACIDENTE,***,***,VIAMÃO,RS,BRASIL,...,2012-01-06,13:00:00,NaN,FINALIZADA,A-070/CENIPA/2013,SIM,2013-11-27,0,1,NÃO
3,45401,45401,45401,45401,ACIDENTE,***,***,SÃO SEBASTIÃO,SP,BRASIL,...,2012-01-06,17:00:00,***,NaN,NaN,NÃO,NaN,0,1,NÃO
4,45407,45407,45407,45407,ACIDENTE,***,***,SÃO SEPÉ,RS,BRASIL,...,2012-01-06,16:30:00,SIM,FINALIZADA,A-071/CENIPA/2013,SIM,2013-11-27,0,1,NÃO

In [13]:
df.loc[df.ocorrencia_uf == 'SP',['ocorrencia_classificacao']]='GRAVE'
#Altera os dados de uma coluna em referencia a outra coluna, neste caso, onde tem o dado 'SP' 
#na coluna UF, será alterado o dado para "Grave", na coluna classificação

In [14]:
df.head()

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
0,52242,52242,52242,52242,INCIDENTE,NaN,NaN,PORTO ALEGRE,RS,BRASIL,...,2012-01-05,20:27:00,***,FINALIZADA,***,NÃO,NaN,0,1,NÃO
1,45331,45331,45331,45331,GRAVE,-23.4355555556,-46.4730555556,GUARULHOS,SP,BRASIL,...,2012-01-06,13:44:00,SIM,FINALIZADA,A-582/CENIPA/2014,SIM,2016-09-01,3,1,NÃO
2,45333,45333,45333,45333,ACIDENTE,***,***,VIAMÃO,RS,BRASIL,...,2012-01-06,13:00:00,NaN,FINALIZADA,A-070/CENIPA/2013,SIM,2013-11-27,0,1,NÃO
3,45401,45401,45401,45401,GRAVE,***,***,SÃO SEBASTIÃO,SP,BRASIL,...,2012-01-06,17:00:00,***,NaN,NaN,NÃO,NaN,0,1,NÃO
4,45407,45407,45407,45407,ACIDENTE,***,***,SÃO SEPÉ,RS,BRASIL,...,2012-01-06,16:30:00,SIM,FINALIZADA,A-071/CENIPA/2013,SIM,2013-11-27,0,1,NÃO

In [15]:
df.loc[df.ocorrencia_uf =='SP']

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
1,45331,45331,45331,45331,GRAVE,-23.4355555556,-46.4730555556,GUARULHOS,SP,BRASIL,...,2012-01-06,13:44:00,SIM,FINALIZADA,A-582/CENIPA/2014,SIM,2016-09-01,3,1,NÃO
3,45401,45401,45401,45401,GRAVE,***,***,SÃO SEBASTIÃO,SP,BRASIL,...,2012-01-06,17:00:00,***,NaN,NaN,NÃO,NaN,0,1,NÃO
5,52243,52243,52243,52243,GRAVE,NaN,NaN,UBATUBA,SP,BRASIL,...,2012-01-06,14:30:00,***,FINALIZADA,***,NÃO,NaN,0,1,NÃO
6,50713,50713,50713,50713,GRAVE,***,***,CAMPINAS,SP,BRASIL,...,2012-01-07,18:15:00,SIM,FINALIZADA,IG-184/CENIPA/2013,SIM,2014-01-08,0,1,NÃO
13,45408,45408,45408,45408,GRAVE,-24.5888888889,-48.2113888889,ELDORADO,SP,BRASIL,...,2012-01-11,13:45:00,SIM,FINALIZADA,A-509/CENIPA/2021,SIM,2021-07-08,1,1,NÃO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5148,80441,80441,80441,80441,GRAVE,-23.0052,-46.6336,BRAGANÇA PAULISTA,SP,BRASIL,...,2021-12-20,18:15:00,NÃO,ATIVA,A DEFINIR,NÃO,NaN,0,1,SIM
5157,80453,80453,80453,80453,GRAVE,-23.00694444444,-47.13444444444,CAMPINAS,SP,BRASIL,...,2021-12-29,09:00:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
5158,80454,80454,80454,80454,GRAVE,-21.144167,-50.426389,ARAÇATUBA,SP,BRASIL,...,2021-12-29,21:35:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,SIM
5161,80456,80456,80456,80456,GRAVE,-23.626111,-46.656389,SÃO PAULO,SP,BRASIL,...,2021-12-30,13:15:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,SIM
5163,80452,80452,80452,80452,GRAVE,-22.585556,-50.753889,MARACAÍ,SP,BRASIL,...,2021-12-31,09:30:00,SIM,ATIVA,A DEFINIR,NÃO,NaN,0,1,NÃO

ocorrencia_uf
**

ocorrencia_aerodromo
****
*****
####
###!

ocorrencia_hora
NULL

In [19]:
df.loc[df.ocorrencia_aerodromo=='****',['ocorrencia_aerodromo']]=pd.NA
df.loc[df.ocorrencia_aerodromo=='####',['ocorrencia_aerodromo']]=pd.NA
df.loc[df.ocorrencia_aerodromo=='*****',['ocorrencia_aerodromo']]=pd.NA

#O comando abaixo limpa todo o dataframe
df.replace(['**','***','###!','####','*****','NULL'], pd.NA, inplace=True)

In [ ]:
df.loc[:,'ocorrencia_aerodromo']

In [27]:
df.isna().sum()
#Verifica a quantidade de dados tipo 'NA ou null' existem na tabela

codigo_ocorrencia1                0
codigo_ocorrencia2                0
codigo_ocorrencia3                0
codigo_ocorrencia4                0
ocorrencia_classificacao          0
ocorrencia_latitude               0
ocorrencia_longitude              0
ocorrencia_cidade                 0
ocorrencia_uf                     0
ocorrencia_pais                   0
ocorrencia_aerodromo              0
ocorrencia_dia                    0
ocorrencia_hora                   0
investigacao_aeronave_liberada    0
investigacao_status               0
divulgacao_relatorio_numero       0
divulgacao_relatorio_publicado    0
divulgacao_dia_publicacao         0
total_recomendacoes               0
total_aeronaves_envolvidas        0
ocorrencia_saida_pista            0
dtype: int64

In [26]:
df.fillna("não informado",inplace = True)
#substitui os dados "na" pelo dado entre parênteses

In [28]:
df.head()

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
0,52242,52242,52242,52242,INCIDENTE,não informado,não informado,PORTO ALEGRE,RS,BRASIL,...,2012-01-05,20:27:00,não informado,FINALIZADA,não informado,NÃO,não informado,0,1,NÃO
1,45331,45331,45331,45331,GRAVE,-23.4355555556,-46.4730555556,GUARULHOS,SP,BRASIL,...,2012-01-06,13:44:00,SIM,FINALIZADA,A-582/CENIPA/2014,SIM,2016-09-01,3,1,NÃO
2,45333,45333,45333,45333,ACIDENTE,não informado,não informado,VIAMÃO,RS,BRASIL,...,2012-01-06,13:00:00,não informado,FINALIZADA,A-070/CENIPA/2013,SIM,2013-11-27,0,1,NÃO
3,45401,45401,45401,45401,GRAVE,não informado,não informado,SÃO SEBASTIÃO,SP,BRASIL,...,2012-01-06,17:00:00,não informado,não informado,não informado,NÃO,não informado,0,1,NÃO
4,45407,45407,45407,45407,ACIDENTE,não informado,não informado,SÃO SEPÉ,RS,BRASIL,...,2012-01-06,16:30:00,SIM,FINALIZADA,A-071/CENIPA/2013,SIM,2013-11-27,0,1,NÃO

In [35]:
#Exclui as colunas
df.drop(['codigo_ocorrencia2','codigo_ocorrencia3','codigo_ocorrencia4','ocorrencia_pais','investigacao_aeronave_liberada'],axis=1,inplace=True)

In [36]:
df.drop_duplicates()
#exclui as linhas duplicadas

,codigo_ocorrencia1,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
0,52242,INCIDENTE,não informado,não informado,PORTO ALEGRE,RS,SBPA,2012-01-05,20:27:00,FINALIZADA,não informado,NÃO,não informado,0,1,NÃO
1,45331,GRAVE,-23.4355555556,-46.4730555556,GUARULHOS,SP,SBGR,2012-01-06,13:44:00,FINALIZADA,A-582/CENIPA/2014,SIM,2016-09-01,3,1,NÃO
2,45333,ACIDENTE,não informado,não informado,VIAMÃO,RS,não informado,2012-01-06,13:00:00,FINALIZADA,A-070/CENIPA/2013,SIM,2013-11-27,0,1,NÃO
3,45401,GRAVE,não informado,não informado,SÃO SEBASTIÃO,SP,não informado,2012-01-06,17:00:00,não informado,não informado,NÃO,não informado,0,1,NÃO
4,45407,ACIDENTE,não informado,não informado,SÃO SEPÉ,RS,não informado,2012-01-06,16:30:00,FINALIZADA,A-071/CENIPA/2013,SIM,2013-11-27,0,1,NÃO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5162,80458,ACIDENTE,-17.999194,-51.642861,JATAÍ,GO,não informado,2021-12-30,20:30:00,ATIVA,A DEFINIR,NÃO,não informado,0,1,NÃO
5163,80452,GRAVE,-22.585556,-50.753889,MARACAÍ,SP,não informado,2021-12-31,09:30:00,ATIVA,A DEFINIR,NÃO,não informado,0,1,NÃO
5164,80457,INCIDENTE GRAVE,-29.695833,-51.081667,NOVO HAMBURGO,RS,SSNH,2021-12-31,11:59:00,FINALIZADA,não informado,NÃO,não informado,0,1,NÃO
5165,80460,INCIDENTE,-25.403333,-49.233611,CURITIBA,PR,SBBI,2021-12-31,15:12:00,FINALIZADA,não informado,NÃO,não informado,0,1,NÃO
5166,80467,INCIDENTE,-9.3675,-40.56361111111,PETROLINA,PE,SBPL,2021-12-31,20:30:00,FINALIZADA,não informado,NÃO,não informado,0,1,NÃO